CREATE DATABASE employee;
USE employee;

CREATE TABLE role (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  title VARCHAR(30) UNIQUE NOT NULL,
  department VARCHAR(30) NOT NULL,
  salary DECIMAL UNSIGNED NOT NULL,
  manager BOOLEAN NOT NULL
);
